[01/Nov/2013 10:53:15] "GET / HTTP/1.1" 200 7063
[01/Nov/2013 10:53:17] "GET / HTTP/1.1" 200 7063
[01/Nov/2013 10:55:39] "GET / HTTP/1.1" 200 7063
[01/Nov/2013 10:55:41] "GET /admin/schedule/department/ HTTP/1.1" 200 2865
[01/Nov/2013 10:55:41] "GET /admin/jsi18n/ HTTP/1.1" 200 5169
[01/Nov/2013 10:56:03] "GET / HTTP/1.1" 200 7063
[01/Nov/2013 10:56:04] "GET / HTTP/1.1" 200 7063
[01/Nov/2013 10:56:06] "GET / HTTP/1.1" 200 7063
[01/Nov/2013 10:56:07] "GET / HTTP/1.1" 200 7063
[01/Nov/2013 10:56:08] "GET / HTTP/1.1" 200 7063
[01/Nov/2013 10:56:10] "GET / HTTP/1.1" 200 7063
[01/Nov/2013 10:56:12] "GET /admin/schedule/event/ HTTP/1.1" 200 2835
[01/Nov/2013 10:56:12] "GET /admin/jsi18n/ HTTP/1.1" 200 5169
[01/Nov/2013 10:56:14] "GET /admin/schedule/event/add/ HTTP/1.1" 200 8637
[01/Nov/2013 10:56:14] "GET /admin/jsi18n/ HTTP/1.1" 200 5169
[01/Nov/2013 10:56:18] "GET /admin/schedule/department/ HTTP/1.1" 200 2865
[01/Nov/2013 10:56:18] "GET /admin/jsi18n/ HTTP/1.1" 200 5169
[01/Nov/2013 10:56:56] "GET /admin/schedule/department/ HTTP/1.1" 200 2865
[01/Nov/2013 10:56:56] "GET /admin/jsi18n/ HTTP/1.1" 200 5169
[01/Nov/2013 10:56:58] "GET /admin/schedule/department/ HTTP/1.1" 200 2865
[01/Nov/2013 10:56:59] "GET /admin/jsi18n/ HTTP/1.1" 200 5169
[01/Nov/2013 10:58:10] "GET /admin/schedule/department/ HTTP/1.1" 200 2865
[01/Nov/2013 10:58:10] "GET /admin/jsi18n/ HTTP/1.1" 200 5169
[01/Nov/2013 10:58:36] "GET /admin/schedule/department/ HTTP/1.1" 200 2865
[01/Nov/2013 10:58:36] "GET /admin/jsi18n/ HTTP/1.1" 200 5169
[01/Nov/2013 10:59:01] "GET /admin/schedule/department/add/ HTTP/1.1" 200 3273
[01/Nov/2013 10:59:01] "GET /admin/jsi18n/ HTTP/1.1" 200 5169
[01/Nov/2013 10:59:12] "POST /admin/schedule/department/add/ HTTP/1.1" 302 0
[01/Nov/2013 10:59:12] "GET /admin/schedule/department/add/ HTTP/1.1" 200 3465
[01/Nov/2013 10:59:12] "GET /admin/jsi18n/ HTTP/1.1" 200 5169
Internal Server Error: /admin/schedule/department/add/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 372, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 202, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 25, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 21, in bound_func
    return func(self, *args2, **kwargs2)
  File "/usr/local/lib/python2.7/dist-packages/django/db/transaction.py", line 223, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 1007, in add_view
    self.save_model(request, new_object, form, False)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 740, in save_model
    obj.save()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 650, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 215, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1675, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 943, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 41, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/postgresql_psycopg2/base.py", line 58, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/postgresql_psycopg2/base.py", line 54, in execute
    return self.cursor.execute(query, args)
DatabaseError: value too long for type character varying(30)

[01/Nov/2013 10:59:22] "POST /admin/schedule/department/add/ HTTP/1.1" 500 157389
[01/Nov/2013 11:00:22] "GET /admin/schedule/ HTTP/1.1" 200 5279
